version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    environment:
      DATABASE_URL: "mysql://root:password@db:3306/needhelp"
    depends_on:
      - db
    networks:
      - needhelp

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/public:/var/www/html/public
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - needhelp

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: needhelp
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - needhelp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - needhelp

  node:
    image: node:16
    container_name: node
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    networks:
      - needhelp

volumes:
  db_data:

networks:
  needhelp:
