version: '3.8'
services:
  # app:
  #   image: 'php:8.2-fpm'
  #   volumes:
  #     - './needhelp/:/var/www/html/'
  #   working_dir: '/var/www/html/'
  #   networks:
  #     - dev

  db:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'needhelp'
    ports:
      - '3306:3306'
    volumes:
      - './database/:/var/lib/mysql'
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - dev

  # web:
  #   image: 'nginx:latest'
  #   volumes:
  #     - './needhelp/:/var/www/html/'
  #     - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
  #   ports:
  #     - '80:80'
  #   depends_on:
  #     - app
  #     - db
  #   networks:
  #     - dev
networks:
  dev:
    driver: bridge
