lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # path private key
    public_key: '%kernel.project_dir%/config/jwt/public.pem'   # path public key
    pass_phrase: '%env(resolve:JWT_PASSPHRASE)%'               # password for the keys
    token_ttl: 3600                                           # time lifecycle
    user_identity_field: email                                  # field for identification
    # token_extractors:
    #     authorization_header:
    #         enabled: true
    #         prefix:  Bearer
    #         name:    Authorization